-- THIS QUERY WILL BE EXECUTED WHEN THE SCHEMA IS LOADED AND WILL APPEAR IN THE LOGS
SELECT 'SCHEMA LOADED SUCCESSFULLY' AS STATUS;

-- CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS COM_D_APP;

-- CREATE SEQUENCES FOR EACH TABLE
CREATE SEQUENCE IF NOT EXISTS COM_D_APP.CMN_DM_USR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS COM_D_APP.PERMISSIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS COM_D_APP.AUTH_DM_SESSION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS COM_D_APP.ACTIVITY_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS COM_D_APP.CMN_TX_DECEASED_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS COM_D_APP.CMN_TX_PAYMENT_SEQ START WITH 1 INCREMENT BY 1;

-- CREATE USERS TABLE
CREATE TABLE IF NOT EXISTS COM_D_APP.CMN_DM_USR (
    SEQ_NO BIGINT DEFAULT NEXT VALUE FOR COM_D_APP.CMN_DM_USR_SEQ NOT NULL, 
    ID VARCHAR(50) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE VARCHAR(50),
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100),
    USER_ID VARCHAR(100),
    GENDER VARCHAR(10),
    DEVICE TEXT,
    LOCATION VARCHAR(50),
    STATUS INTEGER,
    REASON TEXT,
    ADDED_BY VARCHAR(50),
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CMN_PK_DM_USR" PRIMARY KEY (ID)
);


-- CREATE PERMISSIONS TABLE
CREATE TABLE IF NOT EXISTS COM_D_APP.PERMISSIONS (
    ID BIGINT DEFAULT NEXT VALUE FOR COM_D_APP.PERMISSIONS_SEQ NOT NULL,
    EMAIL VARCHAR(50),
    ROLE VARCHAR(50),
    ACCOUNT_TYPE VARCHAR(50),
    CAN_VIEW_LOCAL_ECONOMIC_ENTERPRISE BOOLEAN DEFAULT FALSE,
    CAN_VIEW_MUNICIPAL_TREASURER BOOLEAN DEFAULT FALSE,
    CAN_VIEW_GUEST BOOLEAN DEFAULT FALSE,
    CAN_VIEW_TOTAL_PAYMENT BOOLEAN DEFAULT FALSE,
    CAN_VIEW_USER_MANAGEMENT BOOLEAN DEFAULT FALSE,
    CAN_VIEW_PROFILING BOOLEAN DEFAULT FALSE,
    CAN_VIEW_MAPPING BOOLEAN DEFAULT FALSE,
    CAN_VIEW_NOTIFICATIONS BOOLEAN DEFAULT FALSE,
    CAN_VIEW_REPORTS BOOLEAN DEFAULT FALSE,
    CAN_VIEW_LOGS BOOLEAN DEFAULT FALSE,
    ACTION_LOCAL_ECONOMIC_ENTERPRISE VARCHAR(50),
    ACTION_MUNICIPAL_TREASURER VARCHAR(50),
    ACTION_GUEST VARCHAR(50),
    ACTION_TOTAL_PAYMENT VARCHAR(50),
    ACTION_USER_MANAGEMENT VARCHAR(50),
    ACTION_PROFILING VARCHAR(50),
    ACTION_MAPPING VARCHAR(50),
    ACTION_NOTIFICATIONS VARCHAR(50),
    ACTION_REPORTS VARCHAR(50),
    ACTION_LOGS VARCHAR(50),
    ACTION_SEARCH_MAP VARCHAR(50),
    STATUS INT DEFAULT 1,
    REASON VARCHAR(50),
    ADDED_BY VARCHAR(50),
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_PERMISSIONS" PRIMARY KEY (ID)
);


-- TABLE FOR AUTH_DM_SESSION
CREATE TABLE IF NOT EXISTS COM_D_APP.AUTH_DM_SESSION (
    ID BIGINT DEFAULT NEXT VALUE FOR COM_D_APP.AUTH_DM_SESSION_SEQ NOT NULL,   
    REDIS_KEY VARCHAR(50) NOT NULL,
    BEARER_TOKEN VARCHAR(500) NOT NULL,
    SESSION_ID VARCHAR(100) NOT NULL,
    EXPIRY TIMESTAMP NOT NULL,
    CONSTRAINT "AUTH_PK_DM_SESSION_SEQ " PRIMARY KEY (ID)
);

-- TABLE FOR ACTIVITY_LOG
CREATE TABLE IF NOT EXISTS COM_D_APP.ACTIVITY_LOG (
    ID BIGINT DEFAULT NEXT VALUE FOR COM_D_APP.ACTIVITY_LOG_SEQ NOT NULL,      
    USER_ID VARCHAR(50) NOT NULL,                  
    ACTION VARCHAR(50) NOT NULL,
    LABEL VARCHAR(50),                           
    ACCOUNT_TYPE VARCHAR(50),                    
    CREATED_DATE TIMESTAMP NOT NULL,
    CONSTRAINT "ACTIVITYP_PK_LOG " PRIMARY KEY (ID)
);


-- TABLE FOR TRANSACTION DECEASED
CREATE TABLE IF NOT EXISTS COM_D_APP.CMN_TX_DECEASED (
    SEQ_NO BIGINT DEFAULT NEXT VALUE FOR COM_D_APP.CMN_TX_DECEASED_SEQ NOT NULL,
    DECEASED_ID VARCHAR(50) NOT NULL,
    LABEL_NAME VARCHAR(100),
    LNAME VARCHAR(100),
    FNAME VARCHAR(100),
    MNAME VARCHAR(100),
    SUFFIX VARCHAR(10),
    ADDRESS TEXT,
    BORN VARCHAR(100),
    DIED VARCHAR(100),
    CMTRY_LOC VARCHAR(100),
    DATE_PERMIT VARCHAR(100),
    NATURE_APP VARCHAR(100),
    LAYER_NICHE VARCHAR(50),
    PAYEE_LNAME VARCHAR(100),
    PAYEE_FNAME VARCHAR(100),
    PAYEE_MNAME VARCHAR(100),
    PAYEE_SUFFIX VARCHAR(10),
    PAYEE_CONTACT VARCHAR(50),
    PAYEE_EMAIL VARCHAR(100),
    PAYEE_ADDRESS TEXT,
    OPT_1 VARCHAR(100),
    OPT_2 VARCHAR(100),
    REMARKS TEXT,
    STATUS INT DEFAULT 1,
    CANVAS_MAP VARCHAR(4000),  
    REASON VARCHAR(50), 
    ADDED_BY VARCHAR(50),
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATEE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CMN_PK_TX_DECEASED" PRIMARY KEY (DECEASED_ID) 
);


-- TABLE FOR TRANSACTION DECEASED PAYMENT
CREATE TABLE IF NOT EXISTS COM_D_APP.CMN_TX_PAYMENT (
    SEQ_NO BIGINT DEFAULT NEXT VALUE FOR COM_D_APP.CMN_TX_PAYMENT_SEQ NOT NULL,   
    DECEASED_ID VARCHAR(50) NOT NULL,      
    DECEASED_NAME VARCHAR(255) NOT NULL,            
    DATE_PAID DATE NOT NULL,                       
    KIND_PAYMENT VARCHAR(255) NOT NULL,             
    PERMIT_NO VARCHAR(100),                         
    ORDER_NO VARCHAR(100),                         
    AMOUNT DECIMAL(10, 2) NOT NULL,                
    NUM_YEARS_PAY INT NOT NULL,                    
    NEXT_PAYMENT_DATE DATE NOT NULL,               
    REASON VARCHAR(255),                           
    STATUS INT DEFAULT 1,                             
    CANVAS_MAP TEXT,                               
    ADDED_BY VARCHAR(50),
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATEE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CMN_PK_TX_PAYMENT" PRIMARY KEY (ORDER_NO) 
);